# Generated by Django 6.0.1 on 2026-01-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAdministratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du service administratif', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description détaillée du service')),
                ('actif', models.BooleanField(default=True, help_text='Indique si le service est actuellement actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='date de création du service')),
            ],
            options={
                'verbose_name': 'Service administratif',
                'verbose_name_plural': 'Services administratifs',
                'ordering': ['nom'],
            },
        ),
    ]
