# Generated by Django 6.0.1 on 2026-01-10 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='date du creneau')),
                ('heure_debut', models.TimeField(help_text='Heure de début du creneau')),
                ('heure_fin', models.TimeField(help_text='Heure de fin du creneau')),
                ('disponible', models.BooleanField(default=True, help_text='Indique si le créneau est disponible à la réservation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création du créneau')),
                ('service', models.ForeignKey(help_text='Service admin concerné par le creneau', on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='services.serviceadministratif')),
            ],
            options={
                'verbose_name': 'Créneau horaie',
                'verbose_name_plural': 'Créneaux horaires',
                'ordering': ['date', 'heure_debut'],
                'unique_together': {('service', 'date', 'heure_debut', 'heure_fin')},
            },
        ),
    ]
