# Generated by Django 6.0.1 on 2026-01-12 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('reserve', 'Réservé'), ('annule', 'Annulé')], default='reserve', help_text='Statut du rendez-vous', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date e création du rendez vous')),
                ('creneau', models.OneToOneField(help_text='Créneau Horaire réservé', on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='scheduling.creneauhoraire')),
                ('utilisateur', models.ForeignKey(help_text='Utilisateur ayant réservé le rendez-vous', on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-date_creation'],
            },
        ),
    ]
